name: Deployment
on:
  workflow_run:
    workflows: [Testing]
    types: [completed]
    branches: [main]
jobs:
  deploy:
    name: Deploy on server (WiP)
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up SSH
        env:
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "$PRIVATE_KEY" > ~/.ssh/ghr
          chmod 600 ~/.ssh/ghr
      - name: Display context
        run: |
          echo ${{ github.workflow_run.event.after }}
          echo ${{ github.workflow_run.event.ref }}
      - name: Run remote command
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: ssh -i ~/.ssh/ghr $USER_NAME@$HOST_NAME 'ls'
