name: Docker
on: workflow_dispatch
jobs:
  push:
    name: Build & push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Create jar
        run: ./mvnw package
      - name: Build Docker image
        env:
          CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
          CONTAINER_TAG: ${{ github.ref_name }}
        run: docker build -t $CONTAINER_NAME:$CONTAINER_TAG -t $CONTAINER_NAME:latest .
      - name: Login to Docker Hub
        env:
          DOCKERHUB_LOGIN: ${{ vars.DOCKERHUB_LOGIN }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_LOGIN --password-stdin
      - name: Push Docker image
        env:
          CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
          CONTAINER_TAG: ${{ github.ref_name }}
        run: |
          docker push $CONTAINER_NAME:$CONTAINER_TAG
          docker push $CONTAINER_NAME:latest
